// icons.js
// Central icon registry. Node definitions and UI reference icons by component,
// so swapping an icon is a one-line change and brand logos stay consistent.
// Brand marks come from Simple Icons (si); UI glyphs from Feather (fi).

import {
    FiDownload,
    FiUpload,
    FiType,
    FiZap,
    FiDatabase,
    FiSearch,
    FiGitBranch,
    FiHash,
    FiPlay,
    FiUploadCloud,
    FiHelpCircle,
    FiX,
    FiChevronDown,
    FiChevronRight,
    FiCheckCircle,
    FiAlertTriangle,
    FiInfo,
    FiMessageCircle,
    FiGlobe,
    FiSliders,
    FiArrowRight,
    FiArrowLeft,
    FiBookOpen,
    FiFileText,
    FiGrid,
    FiUsers,
    FiDollarSign,
    FiTarget,
    FiHeadphones,
    FiPlus,
    FiMonitor,
    FiEdit3,
    FiLayers,
    FiSun,
    FiMoon,
    FiCornerUpLeft,
    FiCornerUpRight,
    FiTrash2,
    FiCopy,
    FiPower,
    FiMaximize,
    FiMaximize2,
    FiMinimize2,
    FiChevronUp,
    FiLayout,
    FiMoreHorizontal,
} from "react-icons/fi";
import {
    SiSlack,
    SiGmail,
    SiNotion,
    SiGoogledrive,
    SiGooglesheets,
    SiAirtable,
    SiHubspot,
    SiSalesforce,
    SiDiscord,
    SiGithub,
    SiOpenai,
    SiHuggingface,
    SiTwilio,
    SiTelegram,
    SiLinear,
    SiStripe,
    SiPostgresql,
    SiMongodb,
    SiGooglecalendar,
    SiAnthropic,
    SiGooglegemini,
    SiWhatsapp,
} from "react-icons/si";

// Re-export UI glyphs under friendly names used across the app.
export const UI = {
    search: FiSearch,
    help: FiHelpCircle,
    close: FiX,
    chevronDown: FiChevronDown,
    chevronRight: FiChevronRight,
    play: FiPlay,
    deploy: FiUploadCloud,
    export: FiArrowRight,
    success: FiCheckCircle,
    warning: FiAlertTriangle,
    info: FiInfo,
    book: FiBookOpen,
    arrowRight: FiArrowRight,
    arrowLeft: FiArrowLeft,
    plus: FiPlus,
    sun: FiSun,
    moon: FiMoon,
    undo: FiCornerUpLeft,
    redo: FiCornerUpRight,
    trash: FiTrash2,
    copy: FiCopy,
    edit: FiEdit3,
    power: FiPower,
    layout: FiLayout,
    maximize: FiMaximize,
    more: FiMoreHorizontal,
    collapse: FiMinimize2,
    expand: FiMaximize2,
    chevronUp: FiChevronUp,
    // category + card glyphs (template gallery)
    grid: FiGrid,
    users: FiUsers,
    chat: FiMessageCircle,
    productivity: FiZap,
    marketing: FiTarget,
    sales: FiDollarSign,
    content: FiEdit3,
    support: FiHeadphones,
    monitor: FiMonitor,
    layers: FiLayers,
    search2: FiSearch,
};

// Node-type icons (referenced by string key from definitions for brevity).
export const NODE_ICONS = {
    input: FiDownload,
    output: FiUpload,
    text: FiType,
    knowledgeBase: FiDatabase,
    webSearch: FiGlobe,
    api: FiZap,
    condition: FiGitBranch,
    math: FiHash,
    transform: FiSliders,
    file: FiFileText,

    // Brand integrations
    openai: SiOpenai,
    anthropic: SiAnthropic,
    gemini: SiGooglegemini,
    huggingface: SiHuggingface,
    slack: SiSlack,
    gmail: SiGmail,
    notion: SiNotion,
    googledrive: SiGoogledrive,
    googlesheets: SiGooglesheets,
    googlecalendar: SiGooglecalendar,
    airtable: SiAirtable,
    hubspot: SiHubspot,
    salesforce: SiSalesforce,
    discord: SiDiscord,
    github: SiGithub,
    twilio: SiTwilio,
    telegram: SiTelegram,
    whatsapp: SiWhatsapp,
    linear: SiLinear,
    stripe: SiStripe,
    postgres: SiPostgresql,
    mongodb: SiMongodb,
};

export const getNodeIcon = (key) => NODE_ICONS[key] || FiZap;
